### PR TITLE
Avoid calling python from python

### PR DESCRIPTION
**Pull request by ercolanelli-leo**
Refactor for everything to be contained under the scraper package.
Solves https://github.com/algolia/docsearch-scraper/issues/305 and ease maintenance.

@ElPicador @maxiloc Could you please ensure all the commands you are using are working with your environment before merging?

### CODE REVIEW

**Comment by maxiloc** [comment]
yes I'll check, thanks

**Comment by ElPicador** [comment]
Seems ok to me

**Comment by ercolanelli-leo** [comment]
I let you merge whenever you feel like it then!

**Comment by blee1170** [comment]
Random internet user says this is good!

👍

**Pull request merged**
