### PR TITLE
resolves #426 make temporary index name configurable

### LINKED ISSUE #426: Assign a unique name to the temporary index
The docsearch scraper writes records to a temporary index, then moves that index into place once scraping is complete. This is done to avoid impacting the primary index when building the replacement. However, it does not consider the case when more than one instance of the docsearch scraper is running at once (as is sometimes the case in CI).

The temporary index is named by appending "_tmp" to the primary index name. Instead, it should append a unique name (perhaps the timestamp plus a random string). This will prevent the records from docsearch scraper instances from getting mixed up. Of course, the last one to finish will still win, but at least the index will have integrity.

A simple solution, of course, is to prevent more than one instance from running at once. But in certain CI environments, that's simple not possible because jobs get distributed across runners (for example, in GitLab CI).

Another simple solution would be to read the temporary index from an environment variable. In fact, this might be best since the CI job can typically offer up a unique ID based on the job number. Perhaps look for the variable INDEX_NAME_TMP.

### PR DESCRIPTION
**Pull request by mojavelinux**
resolves #426

reads from INDEX_NAME_TMP environment variable, if set

### CODE REVIEW

**Comment by mojavelinux** [comment]
Let me know if you want to read the environment variable in the config loader and pass it as an argument to the algolia helper constructor.

Also let me know if you need me to update docs anywhere.

**Comment by s-pace** [comment]
Since this PR solves an individual need, I would rather have this at the configuration level.

Thank you for your contribution @mojavelinux

**Comment by mojavelinux** [comment]
Does that mean you like the current approach, or are you suggesting a different approach? I'm happy to update either way, as long as there's some way to control the name.

**Comment by s-pace** [comment]
It would be better if you could update this PR and include it from the config_loader as you did with #429

That's a great job

**Comment by mojavelinux** [comment]
I made the changes that you requested. Is there anything else you need me to change to prepare this PR to be merged?

**Comment by mojavelinux** [comment]
My mistake. It looks like I didn't update it after all. I'll do that now.

**Comment by mojavelinux** [comment]
Okay, updated. It's now possible to set the name of the tmp index directly in the config file:

```json
{
  "index_name": "name_of_site",
  "index_name_tmp: "name_of_site_tmp",
  ...
}
```

though the `INDEX_NAME_TMP` environment variable still wins out if set (so it can be randomized by a CI job).

Do I need to submit documentation before this can be merged?

**Comment by mojavelinux** [comment]
I'm happy to add documentation. Just let me know if we're at that stage and I'll proceed.

**Comment by mojavelinux** [comment]
I just realize I did already added documentation here: https://github.com/algolia/docsearch/pull/584

**Pull request merged**
