### PR TITLE
Put cli back to cli and deployer back to deployer

### PR DESCRIPTION
**Pull request by ercolanelli-leo**
Ok I checked basic stuff like deploying config, changing emails and running configs with anchor/js/no js, and it works, let's test on *every possible* command this time.

(python 3 still broken for the moment, just waiting for this fix to pass before fixing it)

### CODE REVIEW

**Comment by ercolanelli-leo** [comment]
@maxiloc @ElPicador

**Comment by maxiloc** [comment]
I am on it

**Comment by maxiloc** [comment]
@ercolanelli-leo Not sure what I did, but I skipped that for sure, I'll finish reviewing when I come back

**Comment by maxiloc** [comment]
Merged, Work fine for all my tests

**Comment by maxiloc** [comment]
@ercolanelli-leo ready for python 3 😄

**Comment by maxiloc** [comment]
Python 3 fixed

**Pull request merged**
